// scaleph-ui-react/src/pages/DEV/ClusterConfigOptions/index.tsx
import {
  FooterToolbar,
  ProCard,
  ProForm,
  ProFormDependency,
  ProFormDigit,
  ProFormGroup,
  ProFormList,
  ProFormSelect,
  ProFormSwitch,
  ProFormText
} from "@ant-design/pro-components";
import {Col, Form, message, Row} from "antd";
import {listDictDataByType} from "@/services/admin/dictData.service";
import {DICT_TYPE, RESOURCE_TYPE} from "@/constant";
import {ResourceListParam} from "@/services/resource/typings";
import {list} from "@/services/resource/resource.service";
import {FlinkClusterConfig} from "@/services/dev/typings";
import {add, update} from "@/services/dev/flinkClusterConfig.service";
import {history, useIntl, useLocation} from 'umi';
import {Dict} from '@/app.d';

const DevBatchJob: React.FC = () => {
  const urlParams = useLocation();
  const intl = useIntl();
  const [form] = Form.useForm();

  const params = urlParams.state as FlinkClusterConfig;

  const configOptions = new Map(Object.entries(params?.configOptions ? params?.configOptions : {}))

  const data = {
    name: params?.name,
    deployMode: params?.deployMode?.value,
    flinkVersion: params?.flinkVersion?.value,
    flinkRelease: params?.flinkRelease?.id,
    resourceProvider: params?.resourceProvider?.value,
    clusterCredential: params?.clusterCredential?.id,
    remark: params?.remark,
    'state.backend': configOptions.get('state.backend'),
    'state.savepoints.dir': configOptions.get('state.savepoints.dir'),
    'state.checkpoints.dir': configOptions.get('state.checkpoints.dir'),
    'execution.checkpointing.mode': configOptions.get('execution.checkpointing.mode'),
    'execution.checkpointing.unaligned': configOptions.get('execution.checkpointing.unaligned'),
    'execution checkpointing interval': configOptions.get('execution checkpointing interval'),
    'execution.checkpointing.externalized-checkpoint-retention': configOptions.get('execution.checkpointing.externalized-checkpoint-retention'),
    'strategy': configOptions.get('restart-strategy'),
    'restart-strategy.fixed-delay.attempts': configOptions.get('restart-strategy.fixed-delay.attempts'),
    'restart-strategy.fixed-delay.delay': configOptions.get('restart-strategy.fixed-delay.delay'),
    'restart-strategy.failure-rate.delay': configOptions.get('restart-strategy.failure-rate.delay'),
    'restart-strategy.failure-rate.failure-rate-interval': configOptions.get('restart-strategy.failure-rate.failure-rate-interval'),
    'restart-strategy.failure-rate.max-failures-per-interval': configOptions.get('restart-strategy.failure-rate.max-failures-per-interval'),
    'restart-strategy.exponential-delay.initial-backoff': configOptions.get('restart-strategy.exponential-delay.initial-backoff'),
    'restart-strategy.exponential-delay.backoff-multiplier': configOptions.get('restart-strategy.exponential-delay.backoff-multiplier'),
    'restart-strategy.exponential-delay.max-backoff': configOptions.get('restart-strategy.exponential-delay.max-backoff'),
    'restart-strategy.exponential-delay.reset-backoff-threshold': configOptions.get('restart-strategy.exponential-delay.reset-backoff-threshold'),
    'restart-strategy.exponential-delay.jitter-factor': configOptions.get('restart-strategy.exponential-delay.jitter-factor'),
    'ha': configOptions.get('high-availability'),
    'high-availability.storageDir': configOptions.get('high-availability.storageDir'),
    'high-availability.cluster-id': configOptions.get('high-availability.cluster-id'),
    'high-availability.zookeeper.path.root': configOptions.get('high-availability.zookeeper.path.root'),
    'high-availability.zookeeper.quorum': configOptions.get('high-availability.zookeeper.quorum'),
    'jobmanager.memory.process.size': configOptions.get('jobmanager.memory.process.size'),
    'jobmanager.memory.flink.size': configOptions.get('jobmanager.memory.flink.size'),
    'taskmanager.memory.process.size': configOptions.get('taskmanager.memory.process.size'),
    'taskmanager.memory.flink.size': configOptions.get('taskmanager.memory.flink.size'),
  }

  configOptions.delete('state.backend')
  configOptions.delete('state.savepoints.dir')
  configOptions.delete('state.checkpoints.dir')
  configOptions.delete('execution.checkpointing.mode')
  configOptions.delete('execution.checkpointing.unaligned')
  configOptions.delete('execution checkpointing interval')
  configOptions.delete('execution.checkpointing.externalized-checkpoint-retention')
  configOptions.delete('restart-strategy')
  configOptions.delete('restart-strategy.fixed-delay.attempts')
  configOptions.delete('restart-strategy.fixed-delay.delay')
  configOptions.delete('restart-strategy.failure-rate.delay')
  configOptions.delete('restart-strategy.failure-rate.failure-rate-interval')
  configOptions.delete('restart-strategy.failure-rate.max-failures-per-interval')
  configOptions.delete('restart-strategy.exponential-delay.initial-backoff')
  configOptions.delete('restart-strategy.exponential-delay.backoff-multiplier')
  configOptions.delete('restart-strategy.exponential-delay.max-backoff')
  configOptions.delete('restart-strategy.exponential-delay.reset-backoff-threshold')
  configOptions.delete('restart-strategy.exponential-delay.jitter-factor')
  configOptions.delete('high-availability')
  configOptions.delete('high-availability.storageDir')
  configOptions.delete('high-availability.cluster-id')
  configOptions.delete('high-availability.zookeeper.path.root')
  configOptions.delete('high-availability.zookeeper.quorum')
  configOptions.delete('jobmanager.memory.process.size')
  configOptions.delete('jobmanager.memory.flink.size')
  configOptions.delete('taskmanager.memory.process.size')
  configOptions.delete('taskmanager.memory.flink.size')

  const options: Array<any> = []
  configOptions.forEach((value, key) => {
    options.push({key: key, value: value})
  })
  data['options'] = options

  return (<div>
    <ProForm
      form={form}
      layout={"horizontal"}
      initialValues={data}
      grid={true}
      rowProps={{gutter: [16, 8]}}
      submitter={{
        render: (props, doms) => {
          return (
            <Row>
              <Col>
                <FooterToolbar>{doms}</FooterToolbar>
              </Col>
            </Row>
          )
        },
        searchConfig: {
          resetText: intl.formatMessage({id: 'app.common.operate.cancel.label'}),
          submitText: intl.formatMessage({id: 'app.common.operate.submit.label'})
        },
        onReset: () => {
          history.back();
        },
      }}
      onFinish={(value) => {
        const options = new Map<string, any>();
        options['state.backend'] = value['state.backend']
        options['state.savepoints.dir'] = value['state.savepoints.dir']
        options['state.checkpoints.dir'] = value['state.checkpoints.dir']
        options['execution.checkpointing.mode'] = value['execution.checkpointing.mode']
        options['execution.checkpointing.unaligned'] = value['execution.checkpointing.unaligned']
        options['execution checkpointing interval'] = value['execution checkpointing interval']
        options['execution.checkpointing.externalized-checkpoint-retention'] = value['execution.checkpointing.externalized-checkpoint-retention']
        options['restart-strategy'] = value['strategy']
        options['restart-strategy.fixed-delay.attempts'] = value['restart-strategy.fixed-delay.attempts']
        options['restart-strategy.fixed-delay.delay'] = value['restart-strategy.fixed-delay.delay']
        options['restart-strategy.failure-rate.delay'] = value['restart-strategy.failure-rate.delay']
        options['restart-strategy.failure-rate.failure-rate-interval'] = value['restart-strategy.failure-rate.failure-rate-interval']
        options['restart-strategy.failure-rate.max-failures-per-interval'] = value['restart-strategy.failure-rate.max-failures-per-interval']
        options['restart-strategy.exponential-delay.initial-backoff'] = value['restart-strategy.exponential-delay.initial-backoff']
        options['restart-strategy.exponential-delay.backoff-multiplier'] = value['restart-strategy.exponential-delay.backoff-multiplier']
        options['restart-strategy.exponential-delay.max-backoff'] = value['restart-strategy.exponential-delay.max-backoff']
        options['restart-strategy.exponential-delay.reset-backoff-threshold'] = value['restart-strategy.exponential-delay.reset-backoff-threshold']
        options['restart-strategy.exponential-delay.jitter-factor'] = value['restart-strategy.exponential-delay.jitter-factor']
        options['high-availability'] = value['ha']
        options['high-availability.storageDir'] = value['high-availability.storageDir']
        options['high-availability.cluster-id'] = value['high-availability.cluster-id']
        options['high-availability.zookeeper.path.root'] = value['high-availability.zookeeper.path.root']
        options['high-availability.zookeeper.quorum'] = value['high-availability.zookeeper.quorum']
        options['jobmanager.memory.process.size'] = value['jobmanager.memory.process.size']
        options['jobmanager.memory.flink.size'] = value['jobmanager.memory.flink.size']
        options['taskmanager.memory.process.size'] = value['taskmanager.memory.process.size']
        options['taskmanager.memory.flink.size'] = value['taskmanager.memory.flink.size']

        value.options?.forEach(function (item: Record<string, any>) {
          options[item.key] = item.value
        })

        const param: FlinkClusterConfig = {
          id: params?.id,
          name: value['name'],
          flinkVersion: {value: value['flinkVersion']},
          resourceProvider: {value: value['resourceProvider']},
          deployMode: {value: value['deployMode']},
          flinkRelease: {id: value['flinkRelease']},
          clusterCredential: {id: value['clusterCredential']},
          remark: value['remark'],
          configOptions: options
        }
        return params?.id ?
          update(param).then((d) => {
            if (d.success) {
              message.success(intl.formatMessage({id: 'app.common.operate.new.success'}));
            } else {
              message.error(d.errorMessage);
            }
          })
            .catch(() => {
              message.error(intl.formatMessage({id: 'app.common.operate.new.failure'}));
            })
            .finally(() => {
              history.back();
            })
          : add(param).then((d) => {
            if (d.success) {
              message.success(intl.formatMessage({id: 'app.common.operate.new.success'}));
            } else {
              message.error(d.errorMessage);
            }
          })
            .catch(() => {
              message.error(intl.formatMessage({id: 'app.common.operate.new.failure'}));
            })
            .finally(() => {
              history.back();
            });
      }}
    >
      <ProCard
        title={'Basic'}
        headerBordered
        collapsible={true}
      >
        <ProForm.Group>
          <ProFormText
            name="name"
            label={intl.formatMessage({id: 'pages.dev.clusterConfig.name'})}
            colProps={{span: 10, offset: 1}}
            rules={[
              {required: true},
              {max: 30},
              {
                pattern: /^[\w\s_]+$/,
                message: intl.formatMessage({id: 'app.common.validate.characterWord3'}),
              },
            ]}
          />
          <ProFormSelect
            name="deployMode"
            label={intl.formatMessage({id: 'pages.dev.clusterConfig.deployMode'})}
            colProps={{span: 10, offset: 1}}
            rules={[{required: true}]}
            showSearch={true}
            dependencies={['resourceProvider']}
            request={(params) => {
              if (params.resourceProvider == '0') {
                const dict: Dict = {label: 'Session', value: '2'}
                return Promise.resolve([dict])
              }
              return listDictDataByType(DICT_TYPE.flinkDeploymentMode)
            }}
          />
          <ProFormSelect
            name="flinkVersion"
            label={intl.formatMessage({id: 'pages.dev.clusterConfig.flinkVersion'})}
            colProps={{span: 10, offset: 1}}
            rules={[{required: true}]}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkVersion)}
          />
          <ProFormSelect
            name="flinkRelease"
            label={intl.formatMessage({id: 'pages.dev.clusterConfig.flinkRelease'})}
            colProps={{span: 10, offset: 1}}
            rules={[{required: true}]}
            showSearch={true}
            dependencies={['flinkVersion']}
            request={(params) => {
              const resourceParam: ResourceListParam = {
                resourceType: RESOURCE_TYPE.flinkRelease,
                label: params.flinkVersion
              }
              return list(resourceParam).then((response) => {
                return response.records.map((item) => {
                  return {label: item.fileName, value: item.id}
                })
              })
            }}
          />
          <ProFormSelect
            name="resourceProvider"
            label={intl.formatMessage({id: 'pages.dev.clusterConfig.resourceProvider'})}
            colProps={{span: 10, offset: 1}}
            rules={[{required: true}]}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkResourceProvider)}
          />
          <ProFormSelect
            name="clusterCredential"
            label={intl.formatMessage({id: 'pages.dev.clusterConfig.clusterCredential'})}
            colProps={{span: 10, offset: 1}}
            rules={[{required: true}]}
            showSearch={true}
            dependencies={['resourceProvider']}
            request={(params) => {
              const resourceParam: ResourceListParam = {
                resourceType: RESOURCE_TYPE.clusterCredential,
                label: params.resourceProvider
              }
              return list(resourceParam).then((response) => {
                return response.records.map((item) => {
                  return {label: item.name, value: item.id}
                })
              })
            }}
          />
          <ProFormText
            name="remark"
            label={intl.formatMessage({id: 'pages.dev.remark'})}
            colProps={{span: 10, offset: 1}}
            rules={[{max: 200}]}
          />
        </ProForm.Group>
      </ProCard>
      <ProCard
        title={'State & Checkpoints & Savepoints'}
        headerBordered
        collapsible={true}
      >
        <ProForm.Group>
          <ProFormSelect
            name="state.backend"
            label={"state.backend"}
            colProps={{span: 10, offset: 1}}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkStateBackend)}
          />
          <ProFormText
            name="state.savepoints.dir"
            label={'state.savepoints.dir'}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormText
            name="state.checkpoints.dir"
            label={"state.checkpoints.dir"}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormSelect
            name="execution.checkpointing.mode"
            label={"execution.checkpointing.mode"}
            colProps={{span: 10, offset: 1}}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkSemantic)}
          />
          <ProFormSwitch
            name="execution.checkpointing.unaligned"
            label={"execution.checkpointing.unaligned"}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormText
            name="execution checkpointing interval"
            label={'execution checkpointing interval'}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormSelect
            name="execution.checkpointing.externalized-checkpoint-retention"
            label={"execution.checkpointing.externalized-checkpoint-retention"}
            colProps={{span: 10, offset: 1}}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkCheckpointRetain)}
          />
        </ProForm.Group>
      </ProCard>
      <ProCard
        title={"Fault Tolerance"}
        headerBordered
        collapsible={true}
      >
        <ProForm.Group>
          <ProFormSelect
            name="strategy"
            label={"restart-strategy"}
            colProps={{span: 10, offset: 1}}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkRestartStrategy)}
          />

          <ProFormDependency name={['strategy']}>
            {({strategy}) => {
              if (strategy == 'fixeddelay') {
                return (
                  <ProForm.Group>
                    <ProFormDigit
                      name="restart-strategy.fixed-delay.attempts"
                      label="restart-strategy.fixed-delay.attempts"
                      min={1}
                      fieldProps={{precision: 0}}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.fixed-delay.delay"
                      label={'restart-strategy.fixed-delay.delay'}
                      colProps={{span: 10, offset: 1}}
                    />
                  </ProForm.Group>
                )
              }
              if (strategy == 'failurerate') {
                return (
                  <ProForm.Group>
                    <ProFormText
                      name="restart-strategy.failure-rate.delay"
                      label={'restart-strategy.failure-rate.delay'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.failure-rate.failure-rate-interval"
                      label={'restart-strategy.failure-rate.failure-rate-interval'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.failure-rate.max-failures-per-interval"
                      label={'restart-strategy.failure-rate.max-failures-per-interval'}
                      colProps={{span: 10, offset: 1}}
                    />

                  </ProForm.Group>
                )
              }
              if (strategy == 'exponentialdelay') {
                return (
                  <ProForm.Group>
                    <ProFormText
                      name="restart-strategy.exponential-delay.initial-backoff"
                      label={'restart-strategy.exponential-delay.initial-backoff'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.exponential-delay.backoff-multiplier"
                      label={'restart-strategy.exponential-delay.backoff-multiplier'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.exponential-delay.max-backoff"
                      label={'restart-strategy.exponential-delay.max-backoff'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.exponential-delay.reset-backoff-threshold"
                      label={'restart-strategy.exponential-delay.reset-backoff-threshold'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="restart-strategy.exponential-delay.jitter-factor"
                      label={'restart-strategy.exponential-delay.jitter-factor'}
                      colProps={{span: 10, offset: 1}}
                    />
                  </ProForm.Group>
                )
              }
              return <ProForm.Group/>;
            }}
          </ProFormDependency>
        </ProForm.Group>
      </ProCard>
      <ProCard
        title={"High Availability"}
        headerBordered
        collapsible={true}
      >
        <ProForm.Group>
          <ProFormSelect
            name="ha"
            label={"high-availability"}
            colProps={{span: 10, offset: 1}}
            showSearch={true}
            request={() => listDictDataByType(DICT_TYPE.flinkHA)}
          />
          <ProFormText
            name="high-availability.storageDir"
            label={'high-availability.storageDir'}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormText
            name="high-availability.cluster-id"
            label={'high-availability.cluster-id'}
            colProps={{span: 10, offset: 1}}
          />

          <ProFormDependency name={['ha']}>
            {({ha}) => {
              if (ha == 'zookeeper') {
                return (
                  <ProForm.Group>
                    <ProFormText
                      name="high-availability.zookeeper.path.root"
                      label={'high-availability.zookeeper.path.root'}
                      colProps={{span: 10, offset: 1}}
                    />
                    <ProFormText
                      name="high-availability.zookeeper.quorum"
                      label={'high-availability.zookeeper.quorum'}
                      colProps={{span: 10, offset: 1}}
                    />
                  </ProForm.Group>
                )
              }
              return <ProForm.Group/>;
            }}
          </ProFormDependency>
        </ProForm.Group>
      </ProCard>
      <ProCard
        title={"Memory Configuration"}
        headerBordered
        collapsible={true}
      >
        <ProForm.Group>
          <ProFormText
            name="jobmanager.memory.process.size"
            label={'jobmanager.memory.process.size'}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormText
            name="jobmanager.memory.flink.size"
            label={'jobmanager.memory.flink.size'}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormText
            name="taskmanager.memory.process.size"
            label={'taskmanager.memory.process.size'}
            colProps={{span: 10, offset: 1}}
          />
          <ProFormText
            name="taskmanager.memory.flink.size"
            label={'taskmanager.memory.flink.size'}
            colProps={{span: 10, offset: 1}}
          />
        </ProForm.Group>
      </ProCard>
      <ProCard
        title={"Additional Config Options"}
        headerBordered
        collapsible={true}
      >
        <ProFormList
          name="options"
        >
          <ProFormGroup>
            <ProFormText
              name="key"
              label={'Options'}
              colProps={{span: 10, offset: 1}}
            />
            <ProFormText
              name="value"
              label={'Value'}
              colProps={{span: 10, offset: 1}}
            />
          </ProFormGroup>
        </ProFormList>
      </ProCard>
    </ProForm>
  </div>);
}

export default DevBatchJob;

// scaleph-ui/src/app/pages/flink/cluster-config-options/cluster-config-options.component.ts
import {DOCUMENT} from '@angular/common';
import {Component, Inject, OnInit} from '@angular/core';
import {Router} from '@angular/router';
import {TranslateService} from '@ngx-translate/core';
import {LoadingService, ModalService} from 'ng-devui';
import {Dict, DICT_TYPE, PRIVILEGE_CODE} from 'src/app/@core/data/app.data';
import {AuthService} from 'src/app/@core/services/auth.service';
import {ClusterConfigService} from "../../../@core/services/flink/cluster-config.service";
import {SysDictDataService} from "../../../@core/services/admin/dict-data.service";

@Component({
  selector: 'app-cluster-config-options',
  templateUrl: './cluster-config-options.component.html',
  styleUrls: ['./cluster-config-options.component.scss'],
})
export class ClusterConfigOptionsComponent implements OnInit {
  PRIVILEGE_CODE = PRIVILEGE_CODE;

  isCollapsed = true;

  flinkStateBackendList: Dict[] = []

  constructor(
    public authService: AuthService,
    @Inject(DOCUMENT) private doc: any,
    private loadingService: LoadingService,
    private translate: TranslateService,
    private modalService: ModalService,
    private dictDataService: SysDictDataService,
    private clusterConfigService: ClusterConfigService,
    private router: Router
  ) {
  }

  ngOnInit(): void {
    this.dictDataService.listByType(DICT_TYPE.flinkStateBackend).subscribe((d) => {
      this.flinkStateBackendList = d;
    });
  }


}

<div class="da-list-wrap">
  <div class="da-content-wrapper">
    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="da-list-header">
            <div class="da-header-left">
              <d-row [dSpace]="15" [dAlign]="'center'" [dSpaceDirection]="'horizontal'">
                <d-col>
                  <div class="da-header-item-label">集群配置</div>
                </d-col>
              </d-row>
            </div>
            <div class="header-right">
              <d-button style="margin-right: 8px" bsStyle="primary" (btnClick)="submitForm()">
                {{ 'app.common.operate.save.label' | translate }}
              </d-button>
              <d-button bsStyle="common">
                {{ 'app.common.operate.cancel.label' | translate }}
              </d-button>
            </div>
          </div>
        </div>
      </d-col>
    </d-row>

    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #basicPanel [isCollapsed]="isBasicCollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: basicPanel.isCollapsed }"></em>
                Basic
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="20">
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label [required]="true" style="flex: 0 0 180px;">name:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="name" [(ngModel)]="formData.name" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label [required]="true" style="flex: 0 0 180px;">资源:</d-form-label>
                          <d-form-control>
                            <d-select name="flinkDeployConfig"
                                      [allowClear]="true"
                                      [enableLazyLoad]="true"
                                      [filterKey]="'name'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkDeployConfigList"
                                      size="sm"
                                      (loadMore)="onFlinkDeployConfigLoadMore($event)"
                                      [(ngModel)]="formData.flinkDeployConfig"></d-select>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label [required]="true" style="flex: 0 0 180px;">备注:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="remark" [(ngModel)]="formData.remark" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label [required]="true" style="flex: 0 0 180px;">Flink 版本:</d-form-label>
                          <d-form-control>
                            <d-select name="flinkRelease"
                                      [allowClear]="true"
                                      [enableLazyLoad]="true"
                                      [filterKey]="'fileName'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkReleaseList"
                                      size="sm"
                                      (loadMore)="onFlinkReleaseLoadMore($event)"
                                      [(ngModel)]="formData.flinkRelease"></d-select>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label [required]="true" style="flex: 0 0 180px;">模式:</d-form-label>
                          <d-form-control>
                            <d-select name="deployMode"
                                      [allowClear]="true"
                                      [filterKey]="'label'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="deployModeList"
                                      size="sm"
                                      [(ngModel)]="formData.deployMode"></d-select>
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                </d-row>
              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>

    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #statePanel [isCollapsed]="isStateCollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: statePanel.isCollapsed }"></em>
                State & Checkpoints & Savepoints
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="20">
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">state.backend:</d-form-label>
                          <d-form-control>
                            <d-select name="state.backend"
                                      [allowClear]="true"
                                      [filterKey]="'label'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkStateBackendList"
                                      size="sm"
                                      [(ngModel)]="formData.configOptions['state.backend']"></d-select>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">state checkpoints dir</d-form-label>
                          <d-form-control>
                            <input dTextInput name="state.checkpoints.dir" [(ngModel)]="formData.configOptions['state.checkpoints.dir']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">execution.checkpointing.mode</d-form-label>
                          <d-form-control>
                            <d-select name="flinkSemantic"
                                      [allowClear]="true"
                                      [filterKey]="'label'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkSemanticList"
                                      size="sm"
                                      [(ngModel)]="formData.configOptions['execution.checkpointing.mode']"></d-select>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">execution.checkpointing.unaligned</d-form-label>
                          <d-form-control>
                            <d-toggle name="execution.checkpointing.unaligned"
                                      [size]="'sm'"
                                      [(ngModel)]="formData.configOptions['execution.checkpointing.unaligned']"></d-toggle>
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">state savepoints dir:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="state.savepoints.dir" [(ngModel)]="formData.configOptions['state.savepoints.dir']"/>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">execution checkpointing interval:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="execution.checkpointing.interval" [(ngModel)]="formData.configOptions['execution.checkpointing.interval']"/>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">execution.checkpointing.externalized-checkpoint-retention</d-form-label>
                          <d-form-control>
                            <d-select name="flinkCheckpointRetain"
                                      [allowClear]="true"
                                      [filterKey]="'label'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkCheckpointRetainList"
                                      size="sm"
                                      [(ngModel)]="formData.configOptions['execution.checkpointing.externalized-checkpoint-retention']"></d-select>
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                </d-row>

              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>

    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #faultPanel [isCollapsed]="isFaultCollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: faultPanel.isCollapsed }"></em>
                Fault Tolerance
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="20">
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">restart-strategy:</d-form-label>
                          <d-form-control>
                            <d-select name="restart-strategy"
                                      [allowClear]="true"
                                      [filterKey]="'label'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkRestartStrategyList"
                                      size="sm"
                                      (valueChange)="onRestartStrategyValueChange($event)"
                                      [(ngModel)]="formData.configOptions['restart-strategy']"></d-select>
                          </d-form-control>
                        </d-form-item>

                        <d-form-item *ngIf="isFixedDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.fixed-delay.attempts:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.fixed-delay.attempts" [(ngModel)]="formData.configOptions['restart-strategy.fixed-delay.attempts']" />
                          </d-form-control>
                        </d-form-item>

                        <d-form-item *ngIf="isFailureRate">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.failure-rate.failure-rate-interval:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.failure-rate.failure-rate-interval" [(ngModel)]="formData.configOptions['restart-strategy.failure-rate.failure-rate-interval']" />
                          </d-form-control>
                        </d-form-item>

                        <d-form-item *ngIf="isExponentialDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.exponential-delay.initial-backoff:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.exponential-delay.initial-backoff" [(ngModel)]="formData.configOptions['restart-strategy.exponential-delay.initial-backoff']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item *ngIf="isExponentialDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.exponential-delay.backoff-multiplier:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.exponential-delay.backoff-multiplier" [(ngModel)]="formData.configOptions['restart-strategy.exponential-delay.backoff-multiplier']" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">

                        <d-form-item *ngIf="isFixedDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.fixed-delay.delay:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.fixed-delay.delay" [(ngModel)]="formData.configOptions['restart-strategy.fixed-delay.delay']" />
                          </d-form-control>
                        </d-form-item>

                        <d-form-item *ngIf="isFailureRate">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.failure-rate.delay:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.failure-rate.delay" [(ngModel)]="formData.configOptions['restart-strategy.failure-rate.delay']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item *ngIf="isFailureRate">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.failure-rate.max-failures-per-interval:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.failure-rate.max-failures-per-interval" [(ngModel)]="formData.configOptions['restart-strategy.failure-rate.max-failures-per-interval']" />
                          </d-form-control>
                        </d-form-item>

                        <d-form-item *ngIf="isExponentialDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.exponential-delay.max-backoff:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.exponential-delay.max-backoff" [(ngModel)]="formData.configOptions['restart-strategy.exponential-delay.max-backoff']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item *ngIf="isExponentialDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.exponential-delay.reset-backoff-threshold:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.exponential-delay.reset-backoff-threshold" [(ngModel)]="formData.configOptions['restart-strategy.exponential-delay.reset-backoff-threshold']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item *ngIf="isExponentialDelay">
                          <d-form-label style="flex: 0 0 180px;">restart-strategy.exponential-delay.jitter-factor:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="restart-strategy.exponential-delay.jitter-factor" [(ngModel)]="formData.configOptions['restart-strategy.exponential-delay.jitter-factor']" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                </d-row>
              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>

    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #haPanel [isCollapsed]="isHACollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: haPanel.isCollapsed }"></em>
                High Availability
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="20">
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">high-availability:</d-form-label>
                          <d-form-control>
                            <d-select name="high-availability"
                                      [allowClear]="true"
                                      [filterKey]="'label'"
                                      [extraConfig]="{ selectedItemWithTemplate: { enable: true } }"
                                      [options]="flinkHAList"
                                      size="sm"
                                      (valueChange)="onHAValueChange($event)"
                                      [(ngModel)]="formData.configOptions['high-availability']"></d-select>
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">high-availability.storageDir:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="high-availability.storageDir" [(ngModel)]="formData.configOptions['high-availability.storageDir']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item *ngIf="isZookeeperHA">
                          <d-form-label style="flex: 0 0 180px;">high-availability.zookeeper.path.root:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="high-availability.zookeeper.path.root" [(ngModel)]="formData.configOptions['high-availability.zookeeper.path.root']" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">high-availability.cluster-id:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="high-availability.cluster-id" [(ngModel)]="formData.configOptions['high-availability.cluster-id']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item *ngIf="isZookeeperHA">
                          <d-form-label style="flex: 0 0 180px;">high-availability.zookeeper.quorum:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="high-availability.zookeeper.quorum" [(ngModel)]="formData.configOptions['high-availability.zookeeper.quorum']" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                </d-row>
              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>


    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #memPanel [isCollapsed]="isMemCollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: memPanel.isCollapsed }"></em>
                Memory Configuration
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="20">
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">jobmanager.memory.process.size:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="jobmanager.memory.process.size" [(ngModel)]="formData.configOptions['jobmanager.memory.process.size']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">jobmanager.memory.flink.size:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="jobmanager.memory.flink.size" [(ngModel)]="formData.configOptions['jobmanager.memory.flink.size']" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                  <d-col [dSpan]="12">
                    <form dForm ngForm [layout]="layoutDirection">
                      <div class="modal-body" style="padding: 0px 0px 0px 0px">
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">taskmanager.memory.process.size:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="taskmanager.memory.process.size" [(ngModel)]="formData.configOptions['taskmanager.memory.process.size']" />
                          </d-form-control>
                        </d-form-item>
                        <d-form-item>
                          <d-form-label style="flex: 0 0 180px;">taskmanager.memory.flink.size:</d-form-label>
                          <d-form-control>
                            <input dTextInput name="taskmanager.memory.flink.size" [(ngModel)]="formData.configOptions['taskmanager.memory.flink.size']" />
                          </d-form-control>
                        </d-form-item>
                      </div>
                    </form>
                  </d-col>
                </d-row>
              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>

    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #logPanel [isCollapsed]="isLogCollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: logPanel.isCollapsed }"></em>
                Log
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="[12, 12]">
                  <d-col [dSpan]="24">
                    <div class="da-list-container">
                      <div class="list-content">
                        <d-row [dSpace]="15" [dAlign]="'center'" [dSpaceDirection]="'horizontal'">
                          <d-col>
                            <div class="da-header-item-label">env.log.dir:</div>
                          </d-col>
                          <d-col>
                            <input dTextInput name="env.log.dir" [(ngModel)]="formData.configOptions['env.log.dir']"/>
                          </d-col>
                        </d-row>
                      </div>
                    </div>
                  </d-col>
                </d-row>
              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>

    <d-row [dGutter]="[12, 12]">
      <d-col [dSpan]="24">
        <div class="da-list-container">
          <div class="list-content">
            <d-panel [type]="'primary'" #additionalPanel [isCollapsed]="isAdditionalCollapsed" [showAnimation]="true">
              <d-panel-header>
                <em class="icon icon-select-arrow" [ngClass]="{ open: additionalPanel.isCollapsed }"></em>
                Additional Configuration
              </d-panel-header>
              <d-panel-body>
                <d-row [dGutter]="[12, 12]">
                  <d-col [dSpan]="24">
                    <div class="da-list-container">
                      <div class="list-content">
                        <d-row [dSpace]="15" [dAlign]="'center'" [dSpaceDirection]="'horizontal'">
                          <d-col>
                            <div class="da-header-item-label">state.savepoints.dir:</div>
                          </d-col>
                          <d-col>
                            <input dTextInput name="state.savepoints.dir"/>
                          </d-col>
                        </d-row>
                      </div>
                    </div>
                  </d-col>
                </d-row>
              </d-panel-body>
            </d-panel>
          </div>
        </div>
      </d-col>
    </d-row>



  </div>
</div>
